name: Update Data

on:
  schedule:
    # 每天凌晨 1 点运行
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Update data
        run: node update-data.js

      - name: Commit and push changes
        uses: stefanzonca/git-commit-and-push-action@master
        with:
          commit_message: 'chore: update data.json'
          branch: main
          add_files: data/data.json
          force_push: true
